import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {fetchStreamRecoveryEvents,fetchStreamRecoveryProcessedEvents,fetchStreamRecoveryStatus,replayStreamRecovery} from '../../api/streamRecoveryApi';
import {Header} from '../../components';
import {useAuth} from '../../auth/useAuth';
import {HttpError} from '../../api/httpClient';
import './StreamRecoveryPage.css';

export default function StreamRecoveryPage(){
  const {status:authStatus}=useAuth();
  const queryClient=useQueryClient();
  const [eventPage,setEventPage]=useState(0);
  const [processedEventPage,setProcessedEventPage]=useState(0);
  const [replayConfirmOpen,setReplayConfirmOpen]=useState(false);
  const [replayMessage,setReplayMessage]=useState<string|null>(null);
  const status=useQuery({queryKey:['admin','stream-recovery','status'],queryFn:fetchStreamRecoveryStatus,enabled:authStatus==='authenticated',refetchInterval:5000});
  const events=useQuery({queryKey:['admin','stream-recovery','events',eventPage],queryFn:()=>fetchStreamRecoveryEvents(eventPage),enabled:authStatus==='authenticated'});
  const processedEvents=useQuery({queryKey:['admin','stream-recovery','processed-events',processedEventPage],queryFn:()=>fetchStreamRecoveryProcessedEvents(processedEventPage),enabled:authStatus==='authenticated'});
  const replay=useMutation({mutationFn:replayStreamRecovery,onSuccess:result=>{
    setReplayConfirmOpen(false);setReplayMessage(result.message);
    void queryClient.invalidateQueries({queryKey:['admin','stream-recovery']});
  }});
  if(authStatus==='initializing')return <div className="cards-mypage standalone-dashboard"><Header/><main className="stream-recovery-page"><p>인증 상태를 확인하고 있습니다.</p></main></div>;
  if(authStatus==='anonymous')return <div className="cards-mypage standalone-dashboard"><Header/><main className="stream-recovery-page recovery-empty"><small>ADMIN CONSOLE</small><h1>Stream 복구 관리자</h1><p>장애 상태와 복구 대상을 확인하려면 관리자 계정으로 로그인해 주세요.</p><div className="recovery-login-guide"><b>로그인</b><span>오른쪽 상단의 로그인 버튼을 눌러 관리자 계정으로 로그인할 수 있습니다.</span></div><Link className="recovery-home-link" to="/">홈으로 이동</Link></main></div>;
  if(status.isPending)return <div className="cards-mypage standalone-dashboard"><Header/><main className="stream-recovery-page"><p>Stream 복구 상태를 불러오는 중입니다.</p></main></div>;
  const noAdminAccess=status.error instanceof HttpError&&status.error.status===403;
  if(status.isError)return <div className="cards-mypage standalone-dashboard"><Header/><main className="stream-recovery-page recovery-empty"><small>ADMIN CONSOLE</small><h1>{noAdminAccess?'관리자 권한이 필요합니다.':'복구 상태를 불러오지 못했습니다.'}</h1><p>{noAdminAccess?'현재 로그인한 계정에는 Stream 복구 권한이 없습니다.':'잠시 후 다시 시도해 주세요.'}</p><button type="button" onClick={()=>void status.refetch()}>다시 시도</button></main></div>;
  const data=status.data;
  return <div className="cards-mypage standalone-dashboard"><Header/><main className="stream-recovery-page">
    <div className="cards-dash-title"><div><small>ADMIN CONSOLE</small><h1>Redis Stream 복구</h1><p>MySQL projection 지연과 오류를 확인하고 안전한 복구를 준비합니다.</p></div></div>
    <section className="recovery-summary" aria-label="projection 상태 요약"><article><small>PROCESSED</small><strong>{data.processedCount.toLocaleString()}</strong><span>{data.latestProcessedAt?`최근 처리 ${new Date(data.latestProcessedAt).toLocaleString('ko-KR')}`:'처리 완료 이벤트 없음'}</span></article><article><small>PENDING</small><strong>{data.pendingCount.toLocaleString()}</strong><span>수신 후 반영 대기 이벤트</span></article><article className={data.errorCount?'danger':''}><small>ERROR</small><strong>{data.errorCount.toLocaleString()}</strong><span>원인 확인이 필요한 이벤트</span></article></section>
    <section className="recovery-target"><div><small>RECOVERY START POINT</small><h2>다음 복구 대상</h2></div><code>{data.firstIncompleteStreamId??'미완료 이벤트가 없습니다.'}</code>{data.firstFailureMessage&&<p className="recovery-error-message">{data.firstFailureMessage}</p>}</section>
    {replayMessage&&<p className="recovery-result" role="status">{replayMessage}</p>}
    <section className="recovery-event-list"><div className="cards-dash-section-head"><div><h2>미완료 projection 이벤트</h2><p>PENDING과 ERROR 이벤트의 원인과 재시도 이력을 확인합니다.</p></div><span>{events.data?.totalElements.toLocaleString()??0}건</span></div>
      {events.isPending?<div className="filter-empty"><b>이벤트 목록을 불러오는 중...</b></div>:events.isError?<div className="filter-empty"><b>이벤트 목록을 불러오지 못했습니다.</b><button type="button" onClick={()=>void events.refetch()}>다시 시도</button></div>:events.data?.content.length?<><div className="recovery-event-table" role="table" aria-label="미완료 projection 이벤트 목록"><div className="recovery-event-row recovery-event-head" role="row"><span>상태</span><span>Stream ID / 이벤트</span><span>경매</span><span>시도</span><span>오류 원인</span></div>{events.data.content.map(event=><div className="recovery-event-row" role="row" key={event.streamId}><span><b className={event.projectionStatus==='ERROR'?'event-error':'event-pending'}>{event.projectionStatus}</b></span><span><code>{event.streamId}</code><small>{event.eventType}</small></span><span>{event.auctionId??'-'}</span><span>{event.attemptCount}회</span><span title={event.failureMessage??undefined}>{event.failureMessage??'projection 대기 중'}</span></div>)}</div>{events.data.totalPages>1&&<div className="recovery-pagination"><button type="button" disabled={eventPage===0} onClick={()=>setEventPage(page=>page-1)}>이전</button><span>{eventPage+1} / {events.data.totalPages}</span><button type="button" disabled={eventPage+1>=events.data.totalPages} onClick={()=>setEventPage(page=>page+1)}>다음</button></div>}</>:<div className="filter-empty"><b>미완료 projection 이벤트가 없습니다.</b></div>}<div className="recovery-actions"><button type="button" onClick={()=>void Promise.all([status.refetch(),events.refetch()])}>새로고침</button><button type="button" className="recovery-replay-button" disabled={!data.errorCount||replay.isPending} onClick={()=>setReplayConfirmOpen(true)}>{replay.isPending?'복구 시작 중...':'오류 해결 후 재처리'}</button><p>ERROR 이벤트부터 DB 이벤트 순서대로 다시 반영합니다.</p></div></section>
    <section className="recovery-processed-list"><div className="cards-dash-section-head"><div><h2>처리 완료 projection 이벤트</h2><p>최근 처리 순으로 10건씩 확인합니다.</p></div><span>전체 {processedEvents.data?.totalElements.toLocaleString()??0}건</span></div>
      {processedEvents.isPending?<div className="filter-empty"><b>처리 완료 이벤트를 불러오는 중...</b></div>:processedEvents.isError?<div className="filter-empty"><b>처리 완료 이벤트를 불러오지 못했습니다.</b><button type="button" onClick={()=>void processedEvents.refetch()}>다시 시도</button></div>:processedEvents.data?.content.length?<><div className="recovery-processed-table" role="table" aria-label="처리 완료 projection 이벤트 목록"><div className="recovery-processed-row recovery-processed-head" role="row"><span>처리 시각</span><span>Stream ID / 이벤트</span><span>경매</span><span>시도</span></div>{processedEvents.data.content.map(event=><div className="recovery-processed-row" role="row" key={event.streamId}><span>{event.processedAt?new Date(event.processedAt).toLocaleString('ko-KR'):'-'}</span><span><code>{event.streamId}</code><small>{event.eventType}</small></span><span>{event.auctionId??'-'}</span><span>{event.attemptCount}회</span></div>)}</div>{processedEvents.data.totalPages>1&&<div className="recovery-pagination"><button type="button" disabled={processedEventPage===0} onClick={()=>setProcessedEventPage(page=>page-1)}>이전</button><span>{processedEventPage+1} / {processedEvents.data.totalPages}</span><button type="button" disabled={processedEventPage+1>=processedEvents.data.totalPages} onClick={()=>setProcessedEventPage(page=>page+1)}>다음</button></div>}</>:<div className="filter-empty"><b>처리 완료 이벤트가 없습니다.</b></div>}</section>
  </main>{replayConfirmOpen&&<div className="recovery-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setReplayConfirmOpen(false)}><section className="recovery-modal" role="dialog" aria-modal="true" aria-labelledby="recovery-replay-title"><small>CAUTION</small><h2 id="recovery-replay-title">미완료 이벤트를 다시 반영할까요?</h2><p>원인이 해결된 것을 확인한 뒤 진행하세요. 첫 ERROR 이벤트 <code>{data.firstIncompleteStreamId}</code>부터 시작해 이후 PENDING 이벤트를 DB 이벤트 ID 순서대로 projection합니다.</p><p className="recovery-modal-warning">재처리 중 다시 실패하면 해당 이벤트에서 멈추고 이후 이벤트는 다시 PENDING으로 유지됩니다.</p>{replay.isError&&<p className="recovery-modal-error">복구 요청에 실패했습니다. 잠시 후 다시 시도해 주세요.</p>}<div><button type="button" onClick={()=>setReplayConfirmOpen(false)} disabled={replay.isPending}>취소</button><button type="button" onClick={()=>replay.mutate()} disabled={replay.isPending}>재처리 시작</button></div></section></div>}</div>;
}
